### ISSUE TITLE
没有找到qq登陆和微博登陆

### ISSUE THREAD

**Issue by zcpdog** [6ag/BaoKanIOS#2]
感谢你的项目, 但是我编译出来, 发现qq登陆和微博登陆没出现在登陆页面, 是不是编译有什么问题? 另外夜间模式也没找到. 

谢谢.

**Comment by 6ag** [comment]
隐藏按钮了，你可以在登录sb文件里打开

**Comment by zcpdog** [comment]
谢谢找到了.
