### ISSUE TITLE
XIB 文件不显示控件

### ISSUE THREAD

**Issue by zcpdog** [6ag/BaoKanIOS#3]
你好 6ag, 
我是ios 新手, 现在正在拜读你的项目, 
我看到项目中很多XIB 文件, 里面明明有控件, 比如label, button, 但是我却在XIB视图里面看不到这些控件,
<img width="1137" alt="screen shot 2016-06-07 at 12 53 48 pm" src="https://cloud.githubusercontent.com/assets/1244159/15872552/ed13631a-2cae-11e6-8e03-1c1e7a82f5b2.png">
当我查看其中的控件, 发现它们的x,y都是0 或者负数, 我在代码中也没找到相关的constraints, 
请教这么设置的原因, 是不是用到了什么xcode插件来设计的? 
希望6ag 能指点一些. 

感谢.

**Comment by 6ag** [comment]
看不到控件，是因为xib界面底部有个约束条件，就是你上图里的w Any | h Any，这个是用于：你的约束是针对什么屏幕的。你修改成iPhone的就可以看到了

**Comment by zcpdog** [comment]
感谢 @6ag ,看到了
