### ISSUE TITLE
will change to swift 3.0?

### ISSUE THREAD

**Issue by tzsh1007** [6ag/BaoKanIOS#4]
Now ,swfit 3.0 has published,compare to swift 2.X, this change is large, and this project will change to swift3.0? If you Agree, I want to try.

**Comment by 6ag** [comment]
Of course, I will also be ready to upgrade to swift3.0 in my spare time.
You can you up. Thanks.

**Comment by 6ag** [comment]
Hi! This project have been upgraded to swift3.0.
